### ISSUE TITLE
plug-on issue

### ISSUE THREAD

**Issue by ViewsOnTop** [thefrosty/custom-login#31]
an  update to the custom-login plug-in sent my Wordpress site offline 

My WP Hosting team fixed the coding issue and suggested I reach out to the plugin author and let them know the issue it caused. They provided error logs to assist:

PHP Parse error: syntax error, unexpected '[' in /home/viewson5/public_html/wp-content/plugins/custom-login/includes/class-cl-wp-login.php on line 54

regards
Margaret Scott

**Comment by thefrosty** [comment]
This is due to your PHP version being out of date. I would suggest asking your hosting company to update your PHP version 7.2, as that error seen is an array shorthand syntax and was allowed as of PHP version >= 5.4. As of WordPress version 5.2 PHP version 5.6.20 or greater is required. See this post: https://wordpress.org/news/2019/04/minimum-php-version-update/

I'll bump the minimum PHP version supported in this plugin though. Note that if and when version 4 comes out it will only support PHP >= 7.1.
